### ISSUE TITLE
Style IsoDoc HTML output

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc-style#1]
The reference style is the ISO HTML style, which is a bit strange looking.

ISO Directives Part 1: 
https://www.iso.org/sites/directives/2017/consolidated/index.xhtml#_idTextAnchor408

ISO Directives Part 2: 
https://www.iso.org/sites/directives/2016/part2/index.xhtml#_idTextAnchor326

@pierrefortier could you help us create a CSS that makes it "feel" like this ISO style but is actually human-optimized?

Thanks!

**Comment by ronaldtse** [comment]
cc: @opoudjis in case of style updates.

**Comment by pierrefortier** [comment]
I've started making some styling updates to the english document. 

Would we want to include the kind of auto-generating TOC and sidebar that we used in the other doc styles?

**Comment by ronaldtse** [comment]
Indeed! Could you help make 2 versions of this template:

* Compliance optimized -- according to the ISO format given in above links as example. Use those font styles.
* Human optimized -- make them look nice.

I believe we want a TOC sidebar for both versions. But maybe styled differently.

Later on we can bolt on additional javascript features to all these documents, such as:

1. In the text body, when a term is defined in terms and definitions, dynamically show the term definition on hover.
2. Footnotes can be shown when you hover on them.
3. Annotations for comments and changes
3. etc.

**Comment by pierrefortier** [comment]
Ok great. I created two styles, one for the ISO format and a designed one. As usual they are both minimalist, but the human oriented one has more design tweaks to make it a more pleasant read. I've also added in the sidebar in both cases.

**Comment by ronaldtse** [comment]
@pierrefortier this looks great in general!

Here are some minor issues that need improvement. Both styling exhibit the same issues mentioned below.

### Figure key

Each figure key should be in 1 line (e.g., "w    mass fraction ...")

<img width="505" alt="screen shot 2018-05-01 at 7 44 45 am" src="https://user-images.githubusercontent.com/11865/39455573-cd5a8d6e-4d13-11e8-868b-6597752107ef.png">

<img width="230" alt="screen shot 2018-05-01 at 7 49 08 am" src="https://user-images.githubusercontent.com/11865/39455681-62401ff2-4d14-11e8-8ce6-9b9c79e8883c.png">

### Notes / Examples should be left aligned

<img width="774" alt="screen shot 2018-05-01 at 7 48 11 am" src="https://user-images.githubusercontent.com/11865/39455651-36c3c194-4d14-11e8-8539-591c926075fb.png">
<img width="810" alt="screen shot 2018-05-01 at 7 47 54 am" src="https://user-images.githubusercontent.com/11865/39455652-37120f8e-4d14-11e8-8988-bea2f9c3808f.png">
<img width="938" alt="screen shot 2018-05-01 at 7 45 07 am" src="https://user-images.githubusercontent.com/11865/39455653-376482d2-4d14-11e8-9827-894e76f98d28.png">


### Figure / table footnotes should be left aligned

<img width="763" alt="screen shot 2018-05-01 at 7 48 18 am" src="https://user-images.githubusercontent.com/11865/39455662-4478b600-4d14-11e8-86c0-7384d88cc382.png">


### Figure caption styling should be the same for figures and subfigures

Currently the subfigure captions are too small in font size.

<img width="271" alt="screen shot 2018-05-01 at 7 44 59 am" src="https://user-images.githubusercontent.com/11865/39455676-5bb4872c-4d14-11e8-8b92-1ca419ec4f64.png">

<img width="585" alt="screen shot 2018-05-01 at 7 44 56 am" src="https://user-images.githubusercontent.com/11865/39455672-58cbb53a-4d14-11e8-955f-c765003b1525.png">

### ISO format specific

The front page cover should also flow when the screen is widened, just like the designed style.

Thanks!

**Comment by pierrefortier** [comment]
Great, thanks! I think all these issues should be fixed now.

**Comment by ronaldtse** [comment]
@pierrefortier this is excellent! Some remaining issues below.

1. One minor issue (just like https://github.com/riboseinc/csd-style/issues/11) is that we wish to change to a custom `<ul><li>` bullet style that is an emdash.

<img width="599" alt="screen shot 2018-05-04 at 10 00 40 am" src="https://user-images.githubusercontent.com/11865/39610324-0835eea4-4f82-11e8-865a-6a403a221d1f.png">

2. The "title" of the standard should be pronounced -- it is not styled at the moment (before the first section, after the header)

<img width="976" alt="screen shot 2018-05-04 at 10 02 20 am" src="https://user-images.githubusercontent.com/11865/39610378-6c75b516-4f82-11e8-9fa7-3c195273e4a6.png">

3. In Annexes, the obligation ("informative" vs "normative") should be less pronounced (maybe smaller font, not bold). The title of the Annex, obligation, should all on the same line. e.g., "**Annex A** (normative) **Determination of defects**"

<img width="466" alt="screen shot 2018-05-04 at 10 02 32 am" src="https://user-images.githubusercontent.com/11865/39610407-a07a015a-4f82-11e8-8b36-1a345e845bc4.png">

**Comment by ronaldtse** [comment]
@opoudjis again, once these issues are fixed, please help merge to asciidoctor-iso. Thanks!

**Comment by pierrefortier** [comment]
Great, thanks. All the issues should be addressed now. :)

**Comment by ronaldtse** [comment]
@pierrefortier almost there!

1. In Terms and Definitions, some times each main term may also have "alternative" or "deprecated" terms. Can we style them? In ISO documents, the terms are placed without vertical spacing with each other to indicate that these are also "terms" but separate from the below "definition". e.g., maybe they should left-align with the main term?

<img width="688" alt="screen shot 2018-05-04 at 11 32 28 pm" src="https://user-images.githubusercontent.com/11865/39640226-e7d5f44e-4ffc-11e8-9ad4-10a7a5252025.png">

2. Lists should have some vertical spacing apart (see the ISO Rice Document here: https://www.iso.org/files/live/sites/isoorg/files/developing_standards/docs/en/model_document-rice_model.pdf)

<img width="669" alt="screen shot 2018-05-04 at 11 32 44 pm" src="https://user-images.githubusercontent.com/11865/39640306-25d562fc-4ffd-11e8-99b3-75083b92992b.png">

Maybe in general text `line-height` should be slightly more generous?

3. In the Annexes when the section has no content, the parent and child headers tend to run into each other with very little vertical spacing.

4. The Notes / Examples currently take up lots of vertical space. Can we reduce them?

5. The footnote reference number is shown as large as normal text. Shouldn't it be smaller and placed higher up?

<img width="768" alt="screen shot 2018-05-05 at 12 46 31 am" src="https://user-images.githubusercontent.com/11865/39640546-e06e60fa-4ffd-11e8-8f8d-ed2b584a8519.png">

**Comment by pierrefortier** [comment]
Great! Those issues should all be addressed now.

**Comment by ronaldtse** [comment]
@pierrefortier indeed everything is good now! Can you help merge the styling to master? Thanks!

**Comment by opoudjis** [comment]
Merge will be on me again.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
