### ISSUE TITLE
Supporting viewing footnotes

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc-style#2]
Currently when you click on a footnote number, you get transported to the end of the document to view the footnote. Is it possible to also dynamically display the footnote at the bottom of the frame when you hover over it so as to not lose context?

@pierrefortier would you be able to help do this?

**Comment by pierrefortier** [comment]
I've added a footnote hover display functionality to address this.

**Comment by ronaldtse** [comment]
Excellent stuff! Except one issue, it's probably good to go. Currently the footnotes in the table don't show the hover, but would be great if they do.

**Comment by pierrefortier** [comment]
Just added the feature. Thanks! :)
